/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolabdio.views.user_auth;

import java.awt.Color;

/**
 *
 * @author aluno
 */
public class TelaRegistroMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistro
     */
    public TelaRegistroMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserTel_txtField = new javax.swing.JTextField();
        UserEspec_txtField = new javax.swing.JTextField();
        UserCrm_txtField = new javax.swing.JTextField();
        UserName_txtField = new javax.swing.JTextField();
        Espec_lbl = new javax.swing.JLabel();
        Name_lbl = new javax.swing.JLabel();
        Tel_lbl = new javax.swing.JLabel();
        Crm_lbl = new javax.swing.JLabel();
        Cad_btn = new javax.swing.JButton();
        Login_btn = new javax.swing.JButton();
        UserPass_passField = new javax.swing.JPasswordField();
        Pass_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Medico");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));

        UserTel_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserTel_txtField.setForeground(java.awt.Color.gray);
        UserTel_txtField.setText("Insira seu telefone");
        UserTel_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserTel_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserTel_txtFieldFocusLost(evt);
            }
        });

        UserEspec_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserEspec_txtField.setForeground(java.awt.Color.gray);
        UserEspec_txtField.setText("Insira sua especialidade");
        UserEspec_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserEspec_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserEspec_txtFieldFocusLost(evt);
            }
        });

        UserCrm_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserCrm_txtField.setForeground(java.awt.Color.gray);
        UserCrm_txtField.setText("Insira seu CRM");
        UserCrm_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserCrm_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserCrm_txtFieldFocusLost(evt);
            }
        });
        UserCrm_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserCrm_txtFieldActionPerformed(evt);
            }
        });

        UserName_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserName_txtField.setForeground(java.awt.Color.gray);
        UserName_txtField.setText("Insira seu nome");
        UserName_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserName_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserName_txtFieldFocusLost(evt);
            }
        });

        Espec_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Espec_lbl.setText("Especialidade");

        Name_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Name_lbl.setText("Nome");

        Tel_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Tel_lbl.setText("Telefone");

        Crm_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Crm_lbl.setText("CRM");

        Cad_btn.setBackground(new java.awt.Color(153, 204, 255));
        Cad_btn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Cad_btn.setText("Cadastrar");
        Cad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_btnActionPerformed(evt);
            }
        });

        Login_btn.setBackground(new java.awt.Color(204, 204, 255));
        Login_btn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Login_btn.setText("Voltar para o Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        UserPass_passField.setForeground(java.awt.Color.gray);
        UserPass_passField.setText("template");
        UserPass_passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserPass_passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserPass_passFieldFocusLost(evt);
            }
        });

        Pass_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Pass_lbl.setText("Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pass_lbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UserPass_passField, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cad_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Crm_lbl)
                                    .addComponent(Tel_lbl)
                                    .addComponent(Name_lbl)
                                    .addComponent(Espec_lbl)
                                    .addComponent(UserName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserCrm_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserEspec_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserTel_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addContainerGap(262, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Name_lbl)
                .addGap(3, 3, 3)
                .addComponent(UserName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tel_lbl)
                .addGap(1, 1, 1)
                .addComponent(UserTel_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Espec_lbl)
                .addGap(1, 1, 1)
                .addComponent(UserEspec_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Crm_lbl)
                .addGap(1, 1, 1)
                .addComponent(UserCrm_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass_lbl)
                .addGap(0, 0, 0)
                .addComponent(UserPass_passField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(Cad_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTel_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserTel_txtFieldFocusGained
        // Placeholder exit
        String user = UserTel_txtField.getText();
        if("".equals(user) || "Insira seu telefone".equals(user)){
            UserTel_txtField.setForeground(Color.BLACK);
            UserTel_txtField.setText("");
        }
    }//GEN-LAST:event_UserTel_txtFieldFocusGained

    private void UserTel_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserTel_txtFieldFocusLost
        // Placeholder back
        String user = UserTel_txtField.getText();
        if("".equals(user) || "Insira seu telefone".equals(user)){
            UserTel_txtField.setForeground(Color.GRAY);
            UserTel_txtField.setText("Insira seu telefone");
        }
    }//GEN-LAST:event_UserTel_txtFieldFocusLost

    private void UserEspec_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserEspec_txtFieldFocusGained
        // Placeholder exit
        String user = UserEspec_txtField.getText();
        if("".equals(user) || "Insira sua especialidade".equals(user)){
            UserEspec_txtField.setForeground(Color.BLACK);
            UserEspec_txtField.setText("");
        }
    }//GEN-LAST:event_UserEspec_txtFieldFocusGained

    private void UserEspec_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserEspec_txtFieldFocusLost
         // Placeholder back
        String user = UserEspec_txtField.getText();
        if("".equals(user) || "Insira sua especialidade".equals(user)){
            UserEspec_txtField.setForeground(Color.GRAY);
            UserEspec_txtField.setText("Insira sua especialidade");
        }
    }//GEN-LAST:event_UserEspec_txtFieldFocusLost

    private void UserCrm_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserCrm_txtFieldFocusGained
        // Placeholder exit
        String user = UserCrm_txtField.getText();
        if("".equals(user) || "Insira seu CRM".equals(user)){
            UserCrm_txtField.setForeground(Color.BLACK);
            UserCrm_txtField.setText("");
        }
    }//GEN-LAST:event_UserCrm_txtFieldFocusGained

    private void UserCrm_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserCrm_txtFieldFocusLost
        // Placeholder back
        String user = UserCrm_txtField.getText();
        if("".equals(user) || "Insira seu CRM".equals(user)){
            UserCrm_txtField.setForeground(Color.GRAY);
            UserCrm_txtField.setText("Insira seu CRM");
        }
    }//GEN-LAST:event_UserCrm_txtFieldFocusLost

    private void UserName_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserName_txtFieldFocusGained
        // Placeholder exit
        String user = UserName_txtField.getText();
        if("".equals(user) || "Insira seu nome".equals(user)){
            UserName_txtField.setForeground(Color.BLACK);
            UserName_txtField.setText("");
        }
    }//GEN-LAST:event_UserName_txtFieldFocusGained

    private void UserName_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserName_txtFieldFocusLost
        // Placeholder back
        String user = UserName_txtField.getText();
        if("".equals(user) || "Insira seu nome".equals(user)){
            UserName_txtField.setForeground(Color.GRAY);
            UserName_txtField.setText("Insira seu nome");
        }
    }//GEN-LAST:event_UserName_txtFieldFocusLost

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // Back to login
        TelaLogin login = new TelaLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_Login_btnActionPerformed

    private void UserPass_passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserPass_passFieldFocusGained
        // Placeholder exit
        String pass = new String(UserPass_passField.getPassword());
        if("".equals(pass) || "template".equals(pass)){
            UserPass_passField.setForeground(Color.BLACK);
            UserPass_passField.setText("");
        }
    }//GEN-LAST:event_UserPass_passFieldFocusGained

    private void UserPass_passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserPass_passFieldFocusLost
        // Placeholder back
        String pass = new String(UserPass_passField.getPassword());
        if("".equals(pass) || "template".equals(pass)){
            UserPass_passField.setForeground(Color.GRAY);
            UserPass_passField.setText("template");
        }
    }//GEN-LAST:event_UserPass_passFieldFocusLost

    private void UserCrm_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserCrm_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserCrm_txtFieldActionPerformed

    private void Cad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_btnActionPerformed
        // Create new user / back to login
        TelaLogin login = new TelaLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_Cad_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cad_btn;
    private javax.swing.JLabel Crm_lbl;
    private javax.swing.JLabel Espec_lbl;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Name_lbl;
    private javax.swing.JLabel Pass_lbl;
    private javax.swing.JLabel Tel_lbl;
    private javax.swing.JTextField UserCrm_txtField;
    private javax.swing.JTextField UserEspec_txtField;
    private javax.swing.JTextField UserName_txtField;
    private javax.swing.JPasswordField UserPass_passField;
    private javax.swing.JTextField UserTel_txtField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
