/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolabdio.views.user_auth;

import projetolabdio.views.user_auth.TelaRegistroMedico;
import projetolabdio.views.TelaMedico;

import java.awt.Color;
import projetolabdio.controllers.LoginController;

/**
 *
 * @author aluno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Crm_txtField = new javax.swing.JTextField();
        Crm_lbl = new javax.swing.JLabel();
        User_passField = new javax.swing.JPasswordField();
        Pass_lbl = new javax.swing.JLabel();
        Login_btn = new javax.swing.JButton();
        Cadastro_lbl = new javax.swing.JLabel();
        Icon_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        Crm_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Crm_txtField.setForeground(java.awt.Color.gray);
        Crm_txtField.setText("Insira seu CRM");
        Crm_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Crm_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Crm_txtFieldFocusLost(evt);
            }
        });
        Crm_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Crm_txtFieldKeyTyped(evt);
            }
        });

        Crm_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Crm_lbl.setText("CRM");

        User_passField.setForeground(java.awt.Color.gray);
        User_passField.setText("template");
        User_passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                User_passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                User_passFieldFocusLost(evt);
            }
        });

        Pass_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Pass_lbl.setText("Senha");

        Login_btn.setBackground(new java.awt.Color(153, 204, 255));
        Login_btn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Login_btn.setText("LOGIN");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        Cadastro_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Cadastro_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cadastro_lbl.setText("<html><u>Não possuo conta</u>");
        Cadastro_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cadastro_lblMouseClicked(evt);
            }
        });

        Icon_lbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 100)); // NOI18N
        Icon_lbl.setText("LadBio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pass_lbl)
                            .addComponent(User_passField, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Crm_lbl)
                            .addComponent(Crm_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Login_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cadastro_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Icon_lbl)
                        .addGap(289, 289, 289))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(Icon_lbl)
                .addGap(56, 56, 56)
                .addComponent(Crm_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Crm_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pass_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(User_passField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cadastro_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crm_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Crm_txtFieldFocusGained
        // Placeholder exit
        String user = Crm_txtField.getText();
        if("".equals(user) || "Insira seu CRM".equals(user)){
            Crm_txtField.setForeground(Color.BLACK);
            Crm_txtField.setText("");
        }
    }//GEN-LAST:event_Crm_txtFieldFocusGained

    private void User_passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_User_passFieldFocusGained
        // Placeholder exit
        String pass = new String(User_passField.getPassword());
        if("".equals(pass) || "template".equals(pass)){
            User_passField.setForeground(Color.BLACK);
            User_passField.setText("");
        }
    }//GEN-LAST:event_User_passFieldFocusGained

    private void Crm_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Crm_txtFieldFocusLost
        // Placeholder back
        String user = Crm_txtField.getText();
        if("".equals(user) || "Insira seu CRM".equals(user)){
            Crm_txtField.setForeground(Color.GRAY);
            Crm_txtField.setText("Insira seu CRM");
        }
    }//GEN-LAST:event_Crm_txtFieldFocusLost

    private void User_passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_User_passFieldFocusLost
        // Placeholder back
        String pass = new String(User_passField.getPassword());
        if("".equals(pass) || "template".equals(pass)){
            User_passField.setForeground(Color.GRAY);
            User_passField.setText("template");
        }
    }//GEN-LAST:event_User_passFieldFocusLost

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // Login
        String crm = Crm_txtField.getText();
        String pass = new String(User_passField.getPassword());
        
        LoginController login = new LoginController();
        
        if(login.Login(crm, pass)){ // Navegate if login sucess
            TelaMedico tMed = new TelaMedico();
            tMed.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Login_btnActionPerformed

    private void Cadastro_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cadastro_lblMouseClicked
        // Register new user
        TelaRegistroMedico registro = new TelaRegistroMedico();
        this.dispose();
        registro.setVisible(true);
    }//GEN-LAST:event_Cadastro_lblMouseClicked

    private void Crm_txtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Crm_txtFieldKeyTyped
        // Accept only numbers
        String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_Crm_txtFieldKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastro_lbl;
    private javax.swing.JLabel Crm_lbl;
    private javax.swing.JTextField Crm_txtField;
    private javax.swing.JLabel Icon_lbl;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Pass_lbl;
    private javax.swing.JPasswordField User_passField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
