/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolabdio.views;


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import projetolabdio.controllers.PacienteController;
import projetolabdio.controllers.PagamentoController;
import projetolabdio.controllers.TratamentoController;
import projetolabdio.views.TelaMedico;
import projetolabdio.models.Paciente;
import projetolabdio.models.Pagamento;
import projetolabdio.models.Tratamento;

/**
 * The individual screen of Paciente
 * @author Gabriel Siqueira
 * @since 01/11/2022
 * @version 1.2 (whitout update system)
 */
public class TelaPacienteR extends javax.swing.JFrame {
    
    // Attributes
    private ArrayList<Integer> id = new ArrayList<>(); // Id List

    /**
     * Creates new form TelaPaciente
     * And set labels with the Paciente obj data
     * And set jList for Tratamento for this Paciente
     * @param p Object Paciente to be instantiated
     */
    public TelaPacienteR(Paciente p) {
        initComponents();
        
        // Set labels
        Nome_lbl.setText(p.getNome());
        Cpf_lbl.setText(p.getCpf());
        Tel_lbl.setText(p.getTelefone());
        End_lbl.setText(p.getEndereco());
        
        // Search and set Tratamento and Pagamento jList
        PacienteController pac = new PacienteController();
        TratamentoController trat = new TratamentoController();
        DefaultListModel model = new DefaultListModel();
        ArrayList<Tratamento> tratamentos = pac.selectTratamento(p.getCpf()); // Select tratamentos
        ArrayList<Pagamento> pagamentos = trat.selectTratamentoPagamento(tratamentos); // Select pagamentos
        
        // Set model
        for(int i=0; i<tratamentos.size(); i++) // Set model jList
            if(pagamentos.get(i).getPago())
                model.addElement(tratamentos.get(i).getData()+" - Pagamento OK");
            else
                model.addElement(tratamentos.get(i).getData()+" - Pagamento Pendente");
        
        for(Tratamento t : tratamentos) // Set CPF list
               id.add(t.getId());

        
        // Set jList
        Trat_jList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nome_lbl = new javax.swing.JLabel();
        Cpf_lbl = new javax.swing.JLabel();
        Tel_lbl = new javax.swing.JLabel();
        End_lbl = new javax.swing.JLabel();
        Trat_lbl = new javax.swing.JLabel();
        Dados_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trat_jList = new javax.swing.JList<>();
        Pac_Delete_btn = new javax.swing.JButton();
        Pac_Update_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        Trat_add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("Endereço:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nome_lbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cpf_lbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tel_lbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(End_lbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nome_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cpf_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tel_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(End_lbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Trat_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Trat_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Trat_lbl.setText("Tratamentos: (Clique para ver detalhes)");

        Dados_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Dados_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Dados_lbl.setText("Dados Paciente:");

        Trat_jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Trat_jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Trat_jList);

        Pac_Delete_btn.setBackground(new java.awt.Color(255, 102, 102));
        Pac_Delete_btn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Pac_Delete_btn.setText("Apagar");
        Pac_Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pac_Delete_btnActionPerformed(evt);
            }
        });

        Pac_Update_btn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Pac_Update_btn.setText("Editar");

        Back_btn.setBackground(new java.awt.Color(204, 204, 255));
        Back_btn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Back_btn.setText("Voltar para o Menu");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        Trat_add_btn.setBackground(new java.awt.Color(0, 255, 51));
        Trat_add_btn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Trat_add_btn.setText("Adicionar tratamento");
        Trat_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trat_add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Dados_lbl)
                            .addComponent(Trat_lbl)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pac_Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Trat_add_btn)
                            .addComponent(Pac_Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Dados_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pac_Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Trat_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pac_Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(Trat_add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Capture double clicks on Trat_jList
     * Call the TratamentoController and PagamentoController to redirect to the individual Tratamento screen
     */
    private void Trat_jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Trat_jListMouseClicked
        // DoubleClick in elements
        if (evt.getClickCount() == 2) {
            int index = Trat_jList.locationToIndex(evt.getPoint());

            // Select Tratamento using id
            TratamentoController trat = new TratamentoController();
            Tratamento t = trat.getTratamento(id.get(index));
            
            // Select Pagameto
            PagamentoController pag = new PagamentoController();
            Pagamento p = pag.getPagamento(t.getId());
            
            // Isso aqui tem q ir pro controllers
            TelaTratamentoR tra = new TelaTratamentoR(t,p);
            this.dispose();
            tra.setVisible(true);
        }
    }//GEN-LAST:event_Trat_jListMouseClicked

    /**
     * Back to the main screen of user, TelaMedico
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // Back to TelaMedico
        TelaMedico medico = new TelaMedico();
        this.dispose();
        medico.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed

    /**
     * Use the PacienteController for delete the Paciente being instantiated on this screen
     * Make a confirmation before delete
     */
    private void Pac_Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pac_Delete_btnActionPerformed
        // Delete Paciente
        boolean req;
        int showConfirmDialog;
        showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Certeza que quer apagar\n"+Nome_lbl.getText()+"?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if(showConfirmDialog == 0){ // Yes == 0
            PacienteController paciente = new PacienteController();
            req = paciente.deletePaciente(Cpf_lbl.getText());
            if (req){
                JOptionPane.showMessageDialog(rootPane, "Paciente deletado com sucesso!", "Deletar", JOptionPane.INFORMATION_MESSAGE);
                // Back to TelaMedico
                TelaMedico med = new TelaMedico();
                med.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Houve um erro ao deletar o Paciente!", "Deletar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Pac_Delete_btnActionPerformed

    /**
     * Go to add new Tratamento for this user, TelaTratamentoC
     */
    private void Trat_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trat_add_btnActionPerformed
        // Add new tratamento
        TelaTratamentoC tratamento = new TelaTratamentoC(Cpf_lbl.getText());
        this.dispose();
        tratamento.setVisible(true);
    }//GEN-LAST:event_Trat_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paciente Paciente = null;
                new TelaPacienteR(Paciente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel Cpf_lbl;
    private javax.swing.JLabel Dados_lbl;
    private javax.swing.JLabel End_lbl;
    private javax.swing.JLabel Nome_lbl;
    private javax.swing.JButton Pac_Delete_btn;
    private javax.swing.JButton Pac_Update_btn;
    private javax.swing.JLabel Tel_lbl;
    private javax.swing.JButton Trat_add_btn;
    private javax.swing.JList<String> Trat_jList;
    private javax.swing.JLabel Trat_lbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
