/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolabdio.views;

import java.awt.Color;
import projetolabdio.controllers.TratamentoController;

/**
 *
 * @author gabri
 */
public class TelaTratamentoC extends javax.swing.JFrame {

    /**
     * Creates new form TelaTratamentoC
     * @param cpf
     */
    public TelaTratamentoC(String cpf) {
        initComponents();
        
        Cpf_txtField.setText(cpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TratDesc_txtField = new javax.swing.JTextField();
        TratPrec_lbl = new javax.swing.JLabel();
        Desc_lbl = new javax.swing.JLabel();
        TratData_lbl = new javax.swing.JLabel();
        Cpf_lbl = new javax.swing.JLabel();
        Cad_btn = new javax.swing.JButton();
        TratData_txtField = new javax.swing.JTextField();
        TratPrec_txtField = new javax.swing.JTextField();
        Cpf_txtField = new javax.swing.JTextField();
        PagParc_lbl = new javax.swing.JLabel();
        PagParc_txtField = new javax.swing.JTextField();
        PagForma_lbl = new javax.swing.JLabel();
        PagForma_txtField = new javax.swing.JTextField();
        PagData_lbl = new javax.swing.JLabel();
        PagData_txtField = new javax.swing.JTextField();
        Back_btn = new javax.swing.JButton();
        Id_txtField = new javax.swing.JTextField();
        TratPrec_lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));

        TratDesc_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TratDesc_txtField.setForeground(java.awt.Color.gray);
        TratDesc_txtField.setText("Insira a descrição");
        TratDesc_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TratDesc_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TratDesc_txtFieldFocusLost(evt);
            }
        });

        TratPrec_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TratPrec_lbl.setText("Preço");

        Desc_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Desc_lbl.setText("Descrição");

        TratData_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TratData_lbl.setText("Data do tratamento");

        Cpf_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Cpf_lbl.setText("CPF");

        Cad_btn.setBackground(new java.awt.Color(153, 204, 255));
        Cad_btn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Cad_btn.setText("Cadastrar");
        Cad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_btnActionPerformed(evt);
            }
        });

        TratData_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TratData_txtField.setForeground(java.awt.Color.gray);
        TratData_txtField.setText("Insira a data (yyyy-mm-dd)");
        TratData_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TratData_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TratData_txtFieldFocusLost(evt);
            }
        });

        TratPrec_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TratPrec_txtField.setForeground(java.awt.Color.gray);
        TratPrec_txtField.setText("Insira o preço");
        TratPrec_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TratPrec_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TratPrec_txtFieldFocusLost(evt);
            }
        });
        TratPrec_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TratPrec_txtFieldKeyTyped(evt);
            }
        });

        Cpf_txtField.setEditable(false);
        Cpf_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Cpf_txtField.setForeground(java.awt.Color.gray);
        Cpf_txtField.setText("Insira o CPF do paciente");
        Cpf_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Cpf_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Cpf_txtFieldFocusLost(evt);
            }
        });

        PagParc_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        PagParc_lbl.setText("Parcelas");

        PagParc_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PagParc_txtField.setForeground(java.awt.Color.gray);
        PagParc_txtField.setText("Insira a quantidade de parcelas");
        PagParc_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PagParc_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PagParc_txtFieldFocusLost(evt);
            }
        });
        PagParc_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PagParc_txtFieldKeyTyped(evt);
            }
        });

        PagForma_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        PagForma_lbl.setText("Formas de pagamento");

        PagForma_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PagForma_txtField.setForeground(java.awt.Color.gray);
        PagForma_txtField.setText("Insira a forma de pagamento");
        PagForma_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PagForma_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PagForma_txtFieldFocusLost(evt);
            }
        });

        PagData_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        PagData_lbl.setText("Data do pagamento");

        PagData_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        PagData_txtField.setForeground(java.awt.Color.gray);
        PagData_txtField.setText("Insira a data (yyyy-mm-dd)");
        PagData_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PagData_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PagData_txtFieldFocusLost(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(204, 204, 255));
        Back_btn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Back_btn.setText("Voltar para o Menu");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        Id_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Id_txtField.setForeground(java.awt.Color.gray);
        Id_txtField.setText("Insira um id");
        Id_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Id_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Id_txtFieldFocusLost(evt);
            }
        });
        Id_txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Id_txtFieldKeyTyped(evt);
            }
        });

        TratPrec_lbl1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TratPrec_lbl1.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cpf_lbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cad_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Desc_lbl)
                                    .addComponent(TratDesc_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap(261, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TratPrec_lbl1)
                            .addComponent(Id_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PagData_lbl)
                            .addComponent(PagData_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PagForma_lbl)
                            .addComponent(PagForma_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PagParc_lbl)
                            .addComponent(PagParc_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cpf_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TratPrec_lbl)
                            .addComponent(TratPrec_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TratData_lbl)
                            .addComponent(TratData_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TratPrec_lbl1)
                        .addGap(1, 1, 1)
                        .addComponent(Id_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(Desc_lbl)
                .addGap(3, 3, 3)
                .addComponent(TratDesc_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TratData_lbl)
                .addGap(1, 1, 1)
                .addComponent(TratData_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TratPrec_lbl)
                .addGap(1, 1, 1)
                .addComponent(TratPrec_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cpf_lbl)
                .addGap(0, 0, 0)
                .addComponent(Cpf_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PagParc_lbl)
                .addGap(0, 0, 0)
                .addComponent(PagParc_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PagForma_lbl)
                .addGap(0, 0, 0)
                .addComponent(PagForma_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PagData_lbl)
                .addGap(1, 1, 1)
                .addComponent(PagData_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Cad_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TratDesc_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TratDesc_txtFieldFocusGained
        String user = TratDesc_txtField.getText();
        if("".equals(user) || "Insira a descrição".equals(user)){
            TratDesc_txtField.setForeground(Color.BLACK);
            TratDesc_txtField.setText("");
        }
    }//GEN-LAST:event_TratDesc_txtFieldFocusGained

    private void TratDesc_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TratDesc_txtFieldFocusLost
        String user = TratDesc_txtField.getText();
        if("".equals(user) || "Insira a descrição".equals(user)){
            TratDesc_txtField.setForeground(Color.GRAY);
            TratDesc_txtField.setText("Insira a descrição");
        }
    }//GEN-LAST:event_TratDesc_txtFieldFocusLost

    private void Cad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_btnActionPerformed
        // Create new Tratamento
        TratamentoController trat = new TratamentoController();
        boolean sucess = trat.createTratamento(Integer.parseInt(Id_txtField.getText()), Cpf_txtField.getText(), Float.parseFloat(TratPrec_txtField.getText()), TratDesc_txtField.getText(), TratData_txtField.getText(), Integer.parseInt(PagParc_txtField.getText()), PagForma_txtField.getText());
        
        if(sucess){ // Navegate if register sucess
            TelaMedico medico = new TelaMedico();
            this.dispose();
            medico.setVisible(true);
        }
    }//GEN-LAST:event_Cad_btnActionPerformed

    private void TratData_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TratData_txtFieldFocusGained
        String user = TratData_txtField.getText();
        if("".equals(user) || "Insira a data (yyyy-mm-dd)".equals(user)){
            TratData_txtField.setForeground(Color.BLACK);
            TratData_txtField.setText("");
        }
    }//GEN-LAST:event_TratData_txtFieldFocusGained

    private void TratData_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TratData_txtFieldFocusLost
        String user = TratData_txtField.getText();
        if("".equals(user) || "Insira a data (yyyy-mm-dd)".equals(user)){
            TratData_txtField.setForeground(Color.GRAY);
            TratData_txtField.setText("Insira a data (yyyy-mm-dd)");
        }
    }//GEN-LAST:event_TratData_txtFieldFocusLost

    private void TratPrec_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TratPrec_txtFieldFocusGained
        String user = TratPrec_txtField.getText();
        if("".equals(user) || "Insira o preço".equals(user)){
            TratPrec_txtField.setForeground(Color.BLACK);
            TratPrec_txtField.setText("");
        }
    }//GEN-LAST:event_TratPrec_txtFieldFocusGained

    private void TratPrec_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TratPrec_txtFieldFocusLost
        String user = TratPrec_txtField.getText();
        if("".equals(user) || "Insira o preço".equals(user)){
            TratPrec_txtField.setForeground(Color.GRAY);
            TratPrec_txtField.setText("Insira o preço");
        }
    }//GEN-LAST:event_TratPrec_txtFieldFocusLost

    private void Cpf_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cpf_txtFieldFocusGained
        String user = Cpf_txtField.getText();
        if("".equals(user) || "Insira o CPF do paciente".equals(user)){
            Cpf_txtField.setForeground(Color.BLACK);
            Cpf_txtField.setText("");
        }
    }//GEN-LAST:event_Cpf_txtFieldFocusGained

    private void Cpf_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cpf_txtFieldFocusLost
        String user = Cpf_txtField.getText();
        if("".equals(user) || "Insira o CPF do paciente".equals(user)){
            Cpf_txtField.setForeground(Color.GRAY);
            Cpf_txtField.setText("Insira o CPF do paciente");
        }
    }//GEN-LAST:event_Cpf_txtFieldFocusLost

    private void PagParc_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagParc_txtFieldFocusGained
        String user = PagParc_txtField.getText();
        if("".equals(user) || "Insira a quantidade de parcelas".equals(user)){
            PagParc_txtField.setForeground(Color.BLACK);
            PagParc_txtField.setText("");
        }
    }//GEN-LAST:event_PagParc_txtFieldFocusGained

    private void PagParc_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagParc_txtFieldFocusLost
        String user = PagParc_txtField.getText();
        if("".equals(user) || "Insira a quantidade de parcelas".equals(user)){
            PagParc_txtField.setForeground(Color.GRAY);
            PagParc_txtField.setText("Insira a quantidade de parcelas");
        }
    }//GEN-LAST:event_PagParc_txtFieldFocusLost

    private void PagForma_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagForma_txtFieldFocusGained
        String user = PagForma_txtField.getText();
        if("".equals(user) || "Insira a forma de pagamento".equals(user)){
            PagForma_txtField.setForeground(Color.BLACK);
            PagForma_txtField.setText("");
        }
    }//GEN-LAST:event_PagForma_txtFieldFocusGained

    private void PagForma_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagForma_txtFieldFocusLost
        String user = PagForma_txtField.getText();
        if("".equals(user) || "Insira a forma de pagamento".equals(user)){
            PagForma_txtField.setForeground(Color.GRAY);
            PagForma_txtField.setText("Insira a forma de pagamento");
        }
    }//GEN-LAST:event_PagForma_txtFieldFocusLost

    private void PagData_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagData_txtFieldFocusGained
        String user = PagData_txtField.getText();
        if("".equals(user) || "Insira a data (yyyy-mm-dd)".equals(user)){
            PagData_txtField.setForeground(Color.BLACK);
            PagData_txtField.setText("");
        }
    }//GEN-LAST:event_PagData_txtFieldFocusGained

    private void PagData_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PagData_txtFieldFocusLost
        String user = PagData_txtField.getText();
        if("".equals(user) || "Insira a data (yyyy-mm-dd)".equals(user)){
            PagData_txtField.setForeground(Color.GRAY);
            PagData_txtField.setText("Insira a data (yyyy-mm-dd)");
        }
    }//GEN-LAST:event_PagData_txtFieldFocusLost

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // Back to TelaMedico
        TelaMedico medico = new TelaMedico();
        this.dispose();
        medico.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed

    private void TratPrec_txtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TratPrec_txtFieldKeyTyped
        // Accept only numbers
        String caracteres="0987654321.";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_TratPrec_txtFieldKeyTyped

    private void PagParc_txtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PagParc_txtFieldKeyTyped
        // Accept only numbers
        String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_PagParc_txtFieldKeyTyped

    private void Id_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Id_txtFieldFocusGained
        String user = Id_txtField.getText();
        if("".equals(user) || "Insira um id".equals(user)){
            Id_txtField.setForeground(Color.BLACK);
            Id_txtField.setText("");
        }
    }//GEN-LAST:event_Id_txtFieldFocusGained

    private void Id_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Id_txtFieldFocusLost
        String user = Id_txtField.getText();
        if("".equals(user) || "Insira um id".equals(user)){
            Id_txtField.setForeground(Color.GRAY);
            Id_txtField.setText("Insira um id");
        }
    }//GEN-LAST:event_Id_txtFieldFocusLost

    private void Id_txtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Id_txtFieldKeyTyped
        // Accept only numbers
        String caracteres="0987654321";
            if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_Id_txtFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTratamentoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTratamentoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTratamentoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTratamentoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String cpf = null;
                new TelaTratamentoC(cpf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton Cad_btn;
    private javax.swing.JLabel Cpf_lbl;
    private javax.swing.JTextField Cpf_txtField;
    private javax.swing.JLabel Desc_lbl;
    private javax.swing.JTextField Id_txtField;
    private javax.swing.JLabel PagData_lbl;
    private javax.swing.JTextField PagData_txtField;
    private javax.swing.JLabel PagForma_lbl;
    private javax.swing.JTextField PagForma_txtField;
    private javax.swing.JLabel PagParc_lbl;
    private javax.swing.JTextField PagParc_txtField;
    private javax.swing.JLabel TratData_lbl;
    private javax.swing.JTextField TratData_txtField;
    private javax.swing.JTextField TratDesc_txtField;
    private javax.swing.JLabel TratPrec_lbl;
    private javax.swing.JLabel TratPrec_lbl1;
    private javax.swing.JTextField TratPrec_txtField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
