/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetolabdio.views;

import java.awt.Color;

import projetolabdio.views.user_auth.TelaLogin;
import projetolabdio.views.user_auth.TelaRegistroMedico;

/**
 *
 * @author aluno
 */
public class TelaPacienteC extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistroPaciente
     */
    public TelaPacienteC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserTel_txtField = new javax.swing.JTextField();
        UserEnderc_txtField = new javax.swing.JTextField();
        UserCpf_txtField = new javax.swing.JTextField();
        UserName_txtField = new javax.swing.JTextField();
        Enderc_lbl = new javax.swing.JLabel();
        Name_lbl = new javax.swing.JLabel();
        Tel_lbl = new javax.swing.JLabel();
        Cpf_lbl = new javax.swing.JLabel();
        Cad_btn = new javax.swing.JButton();
        Login_btn = new javax.swing.JButton();
        Nasc_lbl = new javax.swing.JLabel();
        UserNasc_txtField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Paciente");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));

        UserTel_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserTel_txtField.setForeground(java.awt.Color.gray);
        UserTel_txtField.setText("Insira seu telefone");
        UserTel_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserTel_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserTel_txtFieldFocusLost(evt);
            }
        });

        UserEnderc_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserEnderc_txtField.setForeground(java.awt.Color.gray);
        UserEnderc_txtField.setText("Insira seu endereco");
        UserEnderc_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserEnderc_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserEnderc_txtFieldFocusLost(evt);
            }
        });

        UserCpf_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserCpf_txtField.setForeground(java.awt.Color.gray);
        UserCpf_txtField.setText("Insira CPF (xxx.xxx.xxx-xx)");
        UserCpf_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserCpf_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserCpf_txtFieldFocusLost(evt);
            }
        });

        UserName_txtField.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserName_txtField.setForeground(java.awt.Color.gray);
        UserName_txtField.setText("Insira seu nome");
        UserName_txtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserName_txtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserName_txtFieldFocusLost(evt);
            }
        });

        Enderc_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Enderc_lbl.setText("Endereço");

        Name_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Name_lbl.setText("Nome");

        Tel_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Tel_lbl.setText("Telefone");

        Cpf_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Cpf_lbl.setText("CPF");

        Cad_btn.setBackground(new java.awt.Color(153, 204, 255));
        Cad_btn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Cad_btn.setText("Cadastrar");
        Cad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_btnActionPerformed(evt);
            }
        });

        Login_btn.setText("Voltar para o Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        Nasc_lbl.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Nasc_lbl.setText("Data de nascimento");

        UserNasc_txtField1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        UserNasc_txtField1.setForeground(java.awt.Color.gray);
        UserNasc_txtField1.setText("Insira sua data de nascimento (dd/mm/yyyy)");
        UserNasc_txtField1.setToolTipText("");
        UserNasc_txtField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserNasc_txtField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserNasc_txtField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cad_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cpf_lbl)
                                    .addComponent(Tel_lbl)
                                    .addComponent(Name_lbl)
                                    .addComponent(Enderc_lbl)
                                    .addComponent(UserName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserCpf_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserEnderc_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UserTel_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap(261, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNasc_txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nasc_lbl))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Name_lbl)
                .addGap(3, 3, 3)
                .addComponent(UserName_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tel_lbl)
                .addGap(1, 1, 1)
                .addComponent(UserTel_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Enderc_lbl)
                .addGap(1, 1, 1)
                .addComponent(UserEnderc_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cpf_lbl)
                .addGap(1, 1, 1)
                .addComponent(UserCpf_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Nasc_lbl)
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(UserNasc_txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(Cad_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTel_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserTel_txtFieldFocusGained
        String user = UserTel_txtField.getText();
        if("".equals(user) || "Insira seu telefone".equals(user)){
            UserTel_txtField.setForeground(Color.BLACK);
            UserTel_txtField.setText("");
        }
    }//GEN-LAST:event_UserTel_txtFieldFocusGained

    private void UserTel_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserTel_txtFieldFocusLost
        String user = UserTel_txtField.getText();
        if("".equals(user) || "Insira seu telefone".equals(user)){
            UserTel_txtField.setForeground(Color.GRAY);
            UserTel_txtField.setText("Insira seu telefone");
        }
    }//GEN-LAST:event_UserTel_txtFieldFocusLost

    private void UserEnderc_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserEnderc_txtFieldFocusGained
        String user = UserEnderc_txtField.getText();
        if("".equals(user) || "Insira seu endereco".equals(user)){
            UserEnderc_txtField.setForeground(Color.BLACK);
            UserEnderc_txtField.setText("");
        }
    }//GEN-LAST:event_UserEnderc_txtFieldFocusGained

    private void UserEnderc_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserEnderc_txtFieldFocusLost
        String user = UserEnderc_txtField.getText();
        if("".equals(user) || "Insira seu endereco".equals(user)){
            UserEnderc_txtField.setForeground(Color.GRAY);
            UserEnderc_txtField.setText("Insira seu endereco");
        }
    }//GEN-LAST:event_UserEnderc_txtFieldFocusLost

    private void UserCpf_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserCpf_txtFieldFocusGained
        String user = UserCpf_txtField.getText();
        if("".equals(user) || "Insira CPF (xxx.xxx.xxx-xx)".equals(user)){
            UserCpf_txtField.setForeground(Color.BLACK);
            UserCpf_txtField.setText("");
        }
    }//GEN-LAST:event_UserCpf_txtFieldFocusGained

    private void UserCpf_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserCpf_txtFieldFocusLost
        String user = UserCpf_txtField.getText();
        if("".equals(user) || "Insira CPF (xxx.xxx.xxx-xx)".equals(user)){
            UserCpf_txtField.setForeground(Color.GRAY);
            UserCpf_txtField.setText("Insira CPF (xxx.xxx.xxx-xx)");
        }
    }//GEN-LAST:event_UserCpf_txtFieldFocusLost

    private void UserName_txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserName_txtFieldFocusGained
        String user = UserName_txtField.getText();
        if("".equals(user) || "Insira seu nome".equals(user)){
            UserName_txtField.setForeground(Color.BLACK);
            UserName_txtField.setText("");
        }
    }//GEN-LAST:event_UserName_txtFieldFocusGained

    private void UserName_txtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserName_txtFieldFocusLost
        String user = UserName_txtField.getText();
        if("".equals(user) || "Insira seu nome".equals(user)){
            UserName_txtField.setForeground(Color.GRAY);
            UserName_txtField.setText("Insira seu nome");
        }
    }//GEN-LAST:event_UserName_txtFieldFocusLost

    private void Cad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_btnActionPerformed
        TelaRegistroMedico tela2 = new TelaRegistroMedico();
        this.dispose();
        tela2.setVisible(true);
    }//GEN-LAST:event_Cad_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        TelaLogin login = new TelaLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_Login_btnActionPerformed

    private void UserNasc_txtField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNasc_txtField1FocusGained
        UserNasc_txtField1.setText("");
        UserNasc_txtField1.setForeground(Color.BLACK);
    }//GEN-LAST:event_UserNasc_txtField1FocusGained

    private void UserNasc_txtField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNasc_txtField1FocusLost
        String user = UserNasc_txtField1.getText();
        if("".equals(user) || "Insira sua data de nascimento (dd/mm/yyyy)".equals(user)){
            UserNasc_txtField1.setForeground(Color.GRAY);
            UserNasc_txtField1.setText("Insira sua data de nascimento (dd/mm/yyyy)");
        }
    }//GEN-LAST:event_UserNasc_txtField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPacienteC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPacienteC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cad_btn;
    private javax.swing.JLabel Cpf_lbl;
    private javax.swing.JLabel Enderc_lbl;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Name_lbl;
    private javax.swing.JLabel Nasc_lbl;
    private javax.swing.JLabel Tel_lbl;
    private javax.swing.JTextField UserCpf_txtField;
    private javax.swing.JTextField UserEnderc_txtField;
    private javax.swing.JTextField UserName_txtField;
    private javax.swing.JTextField UserNasc_txtField1;
    private javax.swing.JTextField UserTel_txtField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
